// llm-frontend/src/views/PromptComparison.tsx
import React, { useState, useEffect, useMemo, useCallback } from 'react'
import { 
  Operation, MagicStick, RefreshLeft, Play, 
  Terminal, Zap, Check, AlertCircle, Loader2, Activity 
} from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { templateAPI, modelConfigAPI, promptTestAPI } from '@/api'
import { useResponsive } from '@/hooks/useResponsive'
import { useMarkdown } from '@/hooks/useMarkdown'
import { useSSEStream } from '@/hooks/useSSEStream'

const PromptComparison: React.FC = () => {
  const { isMobile } = useResponsive()
  const { renderMarkdown } = useMarkdown()
  const { fetchSSE } = useSSEStream()

  const [config, setConfig] = useState({
    templateName: '',
    model: '',
    stream: false,
    variables: ''
  })

  const [templates, setTemplates] = useState<any[]>([])
  const [availableModels, setAvailableModels] = useState<any[]>([])
  const [promptA, setPromptA] = useState('')
  const [promptB, setPromptB] = useState('')
  const [comparing, setComparing] = useState(false)

  const [resultA, setResultA] = useState<any>({ status: '', content: '', tokenUsage: null, duration: 0 })
  const [resultB, setResultB] = useState<any>({ status: '', content: '', tokenUsage: null, duration: 0 })

  const loadData = useCallback(async () => {
    try {
      const [tRes, mRes]: [any, any] = await Promise.all([
        templateAPI.getAll(),
        modelConfigAPI.getAll()
      ])
      setTemplates(tRes || [])
      const models = (mRes || []).map((m: any) => ({
        code: m.modelCode,
        name: m.modelName,
        provider: m.provider
      }))
      setAvailableModels(models)
      if (models.length > 0) {
        setConfig(prev => ({ ...prev, model: models[0].code }))
      }
    } catch (error) {
      console.error(error)
    }
  }, [])

  useEffect(() => {
    loadData()
  }, [loadData])

  const handleTemplateChange = async (templateName: string) => {
    try {
      const template: any = await templateAPI.getByName(templateName)
      setPromptA(template.templateContent)
      setPromptB(template.templateContent)
      setConfig(prev => ({ ...prev, templateName }))
      setResultA({ status: '', content: '', tokenUsage: null, duration: 0 })
      setResultB({ status: '', content: '', tokenUsage: null, duration: 0 })
    } catch (error) {
      console.error(error)
    }
  }

  const loadTemplateVariables = async () => {
    if (!config.templateName) return
    try {
      const variables: any = await promptTestAPI.getTemplateVariables(config.templateName)
      setConfig(prev => ({ ...prev, variables: JSON.stringify(variables, null, 2) }))
    } catch (error) {
      console.error(error)
    }
  }

  const executePrompt = async (version: 'A' | 'B', promptContent: string, variables: any) => {
    const setResult = version === 'A' ? setResultA : setResultB
    const startTime = Date.now()

    try {
      let renderedPrompt = promptContent
      for (const [key, value] of Object.entries(variables)) {
        renderedPrompt = renderedPrompt.replaceAll(`{${key}}`, value as string)
      }

      setResult({ status: 'loading', content: '', tokenUsage: null, duration: 0 })

      let currentContent = ''
      await fetchSSE(config.stream ? '/chat/stream' : '/chat', {
        conversationId: `comparison-${version}-${Date.now()}`,
        message: renderedPrompt,
        model: config.model
      }, {
        onContent: (content) => {
          currentContent += content
          setResult((prev: any) => ({ ...prev, content: currentContent }))
        },
        onTokenUsage: (tokenUsage) => {
          setResult((prev: any) => ({ ...prev, tokenUsage }))
        }
      })

      setResult((prev: any) => ({ 
        ...prev, 
        status: 'success', 
        duration: Date.now() - startTime 
      }))
    } catch (error: any) {
      setResult({ 
        status: 'error', 
        content: `执行失败: ${error.message}`,
        tokenUsage: null,
        duration: 0
      })
    }
  }

  const handleCompare = async () => {
    let variables
    try {
      variables = JSON.parse(config.variables)
    } catch {
      return
    }

    setComparing(true)
    await Promise.all([
      executePrompt('A', promptA, variables),
      executePrompt('B', promptB, variables)
    ])
    setComparing(false)
  }

  const canCompare = config.templateName && config.model && promptA && promptB && config.variables

  return (
    <div className="max-w-7xl mx-auto space-y-12">
      
      {/* 顶部控制台 */}
      <header className="flex items-center justify-between px-6 flex-wrap gap-6">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 neo-convex rounded-2xl flex items-center justify-center text-primary shadow-lg">
            <Operation size={24} />
          </div>
          <div>
            <h1 className="text-2xl font-black tracking-tighter uppercase italic">Prompt A/B Matrix</h1>
            <p className="text-[10px] font-bold text-foreground/30 uppercase tracking-[0.2em]">Parallel Prompt Evaluation</p>
          </div>
        </div>
        <button 
          onClick={handleCompare}
          disabled={!canCompare || comparing}
          className={`h-14 px-8 neo-convex rounded-2xl flex items-center gap-3 font-black tracking-widest transition-all ${
            canCompare && !comparing ? 'text-primary active:scale-95 shadow-xl' : 'text-foreground/10'
          }`}
        >
          {comparing ? <Loader2 size={18} className="animate-spin" /> : <Play size={18} />}
          <span>START COMPARISON</span>
        </button>
      </header>

      {/* 配置面板 */}
      <section className="grid grid-cols-1 xl:grid-cols-12 gap-8 items-stretch">
        <div className="xl:col-span-5 neo-convex rounded-[3rem] p-8 border border-white/40 space-y-6">
          <div className="flex items-center gap-3 px-2">
            <div className="w-8 h-8 neo-concave rounded-xl flex items-center justify-center text-foreground/30">
              <Terminal size={14} />
            </div>
            <span className="text-[10px] font-black tracking-widest text-foreground/40 uppercase">Global Configuration</span>
          </div>

          <div className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="neo-concave rounded-2xl p-1">
                <select 
                  value={config.templateName} 
                  onChange={(e) => handleTemplateChange(e.target.value)}
                  className="w-full bg-transparent border-none focus:outline-none px-4 py-3 text-xs font-bold text-primary appearance-none cursor-pointer"
                >
                  <option value="">Select Template...</option>
                  {templates.map(t => <option key={t.templateName} value={t.templateName}>{t.templateName}</option>)}
                </select>
              </div>
              <div className="neo-concave rounded-2xl p-1">
                <select 
                  value={config.model} 
                  onChange={(e) => setConfig({ ...config, model: e.target.value })}
                  className="w-full bg-transparent border-none focus:outline-none px-4 py-3 text-xs font-bold text-primary appearance-none cursor-pointer"
                >
                  {availableModels.map(m => <option key={m.code} value={m.code}>{m.name}</option>)}
                </select>
              </div>
            </div>
            
            <div className="flex items-center justify-between px-4 neo-concave rounded-2xl py-3">
              <span className="text-[10px] font-black text-foreground/40 tracking-widest uppercase">Stream Mode</span>
              <button 
                onClick={() => setConfig({...config, stream: !config.stream})}
                className={`w-12 h-6 rounded-full transition-all relative ${config.stream ? 'bg-primary shadow-lg shadow-primary/20' : 'neo-concave'}`}
              >
                <div className={`absolute top-1 w-4 h-4 rounded-full bg-white transition-all ${config.stream ? 'right-1' : 'left-1 bg-foreground/20'}`} />
              </button>
            </div>
          </div>
        </div>

        <div className="xl:col-span-7 neo-convex rounded-[3rem] p-8 border border-white/40 flex flex-col">
          <div className="flex items-center justify-between px-2 mb-6">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 neo-concave rounded-xl flex items-center justify-center text-foreground/30">
                <MagicStick size={14} />
              </div>
              <span className="text-[10px] font-black tracking-widest text-foreground/40 uppercase">Variable Injection (JSON)</span>
            </div>
            <button 
              onClick={loadTemplateVariables}
              className="text-[9px] font-black text-primary hover:opacity-80 transition-all uppercase tracking-widest"
            >
              Load Example
            </button>
          </div>
          <div className="flex-1 neo-concave rounded-[2rem] p-1">
            <textarea 
              value={config.variables}
              onChange={(e) => setConfig({ ...config, variables: e.target.value })}
              placeholder='{"key": "value"}'
              className="w-full h-full bg-transparent border-none focus:outline-none px-6 py-4 text-xs font-mono resize-none min-h-[120px]"
            />
          </div>
        </div>
      </section>

      {/* 内容对比区域 */}
      <section className="grid grid-cols-1 lg:grid-cols-2 gap-10">
        <div className="space-y-4">
          <div className="flex items-center justify-between px-6">
            <span className="text-[10px] font-black tracking-widest text-green-500 uppercase">Version A: Baseline</span>
            <Check size={14} className="text-green-500/40" />
          </div>
          <div className="neo-convex rounded-[3rem] p-1 overflow-hidden border border-white/40">
            <textarea 
              value={promptA} 
              readOnly 
              className="w-full h-80 bg-foreground/[0.02] border-none focus:outline-none px-8 py-8 text-sm font-mono leading-relaxed resize-none opacity-60"
              placeholder="Select template to load..."
            />
          </div>
        </div>

        <div className="space-y-4">
          <div className="flex items-center justify-between px-6">
            <span className="text-[10px] font-black tracking-widest text-primary uppercase">Version B: Challenger</span>
            <button 
              onClick={() => setPromptB(promptA)}
              className="text-[9px] font-black text-foreground/30 hover:text-primary transition-all uppercase tracking-widest flex items-center gap-1"
            >
              <RefreshLeft size={10} /> Reset
            </button>
          </div>
          <div className="neo-convex rounded-[3rem] p-1 overflow-hidden border border-white/40">
            <textarea 
              value={promptB} 
              onChange={(e) => setPromptB(e.target.value)}
              className="w-full h-80 bg-transparent border-none focus:outline-none px-8 py-8 text-sm font-mono leading-relaxed resize-none"
              placeholder="Modify prompt to test differences..."
            />
          </div>
        </div>
      </section>

      {/* 结果对比区域 */}
      <section className="grid grid-cols-1 lg:grid-cols-2 gap-10">
        {[ {res: resultA, label: 'A OUTPUT'}, {res: resultB, label: 'B OUTPUT'} ].map((item, idx) => (
          <div key={idx} className="flex flex-col neo-convex rounded-[3.5rem] overflow-hidden border border-white/40 min-h-[400px]">
            <div className="p-8 border-b border-foreground/5 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className={`w-8 h-8 neo-concave rounded-xl flex items-center justify-center ${idx === 0 ? 'text-green-500' : 'text-primary'}`}>
                  <Zap size={14} />
                </div>
                <span className="text-[10px] font-black tracking-widest text-foreground/40 uppercase">{item.label}</span>
              </div>
              {item.res.status === 'loading' && <Loader2 size={16} className="animate-spin text-primary" />}
              {item.res.status === 'success' && <div className="w-2 h-2 rounded-full bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.6)]" />}
              {item.res.status === 'error' && <AlertCircle size={16} className="text-red-500" />}
            </div>

            <div className="flex-1 p-10 overflow-y-auto relative no-scrollbar">
              <article 
                className="markdown-rendered prose prose-slate dark:prose-invert max-w-none"
                dangerouslySetInnerHTML={{ __html: renderMarkdown(item.res.content || '> Waiting for execution...') }}
              />
            </div>

            {item.res.tokenUsage && (
              <footer className="p-6 bg-foreground/[0.01] border-t border-foreground/5 flex items-center gap-6">
                <div className="flex items-center gap-2 text-[9px] font-black text-foreground/20 uppercase tracking-widest">
                  <Activity size={10} /> Metrics
                </div>
                <div className="flex-1 h-[1px] bg-foreground/5" />
                <span className="text-[10px] font-mono text-primary font-bold">TOKENS: {item.res.tokenUsage.totalTokens}</span>
                <span className="text-[10px] font-mono text-foreground/40">{item.res.duration}ms</span>
              </footer>
            )}
          </div>
        ))}
      </section>

    </div>
  )
}

export default PromptComparison

// llm-frontend/src/views/PromptComparison.vue
<template>
  <div class="prompt-comparison">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>Prompt A/B 对比测试</span>
          <el-button type="primary" @click="handleCompare" :loading="comparing" :disabled="!canCompare">
            <el-icon><Operation /></el-icon>
            开始对比
          </el-button>
        </div>
      </template>

      <!-- 配置区域 -->
      <el-form :model="config" :label-width="isMobile ? '100%' : '120px'" :label-position="isMobile ? 'top' : 'right'">
        <el-row :gutter="20">
          <el-col :xs="24" :sm="24" :md="12" :lg="12">
            <el-divider content-position="left">基础配置</el-divider>
            
            <el-form-item label="选择模板">
              <el-select 
                v-model="config.templateName" 
                placeholder="请选择模板" 
                style="width: 100%"
                @change="handleTemplateChange"
                filterable
              >
                <el-option
                  v-for="template in templates"
                  :key="template.templateName"
                  :label="`${template.templateName} (${template.category})`"
                  :value="template.templateName"
                />
              </el-select>
            </el-form-item>

            <el-form-item label="模型">
              <el-select v-model="config.model" placeholder="选择模型" style="width: 100%" filterable>
                <el-option
                  v-for="model in availableModels"
                  :key="model.code"
                  :label="`${model.name} (${model.provider})`"
                  :value="model.code"
                />
              </el-select>
            </el-form-item>

            <el-form-item label="输出模式">
              <el-switch
                v-model="config.stream"
                active-text="流式"
                inactive-text="非流式"
              />
            </el-form-item>
          </el-col>

          <el-col :xs="24" :sm="24" :md="12" :lg="12">
            <el-divider content-position="left">变量配置</el-divider>
            
            <el-form-item label="变量 JSON">
              <el-input
                v-model="config.variables"
                type="textarea"
                :rows="6"
                placeholder='{"key": "value"}'
              />
              <el-button 
                size="small" 
                type="primary" 
                link 
                @click="loadTemplateVariables"
                style="margin-top: 8px"
              >
                <el-icon><MagicStick /></el-icon>
                加载模板示例变量
              </el-button>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>

      <!-- Prompt 对比区域 -->
      <el-divider content-position="left">Prompt 内容对比</el-divider>
      
      <el-row :gutter="20">
        <el-col :xs="24" :sm="24" :md="12" :lg="12">
          <div class="prompt-section">
            <div class="section-header">
              <span class="section-title">A版本：原始模板</span>
              <el-tag type="success">基准版本</el-tag>
            </div>
            <el-input
              v-model="promptA"
              type="textarea"
              :rows="12"
              readonly
              placeholder="选择模板后自动加载"
            />
          </div>
        </el-col>

        <el-col :xs="24" :sm="24" :md="12" :lg="12">
          <div class="prompt-section">
            <div class="section-header">
              <span class="section-title">B版本：调整后模板</span>
              <el-tag type="warning">测试版本</el-tag>
            </div>
            <el-input
              v-model="promptB"
              type="textarea"
              :rows="12"
              placeholder="在此修改 Prompt 内容进行对比测试"
            />
            <el-button 
              size="small" 
              type="primary" 
              link 
              @click="resetPromptB"
              style="margin-top: 8px"
            >
              <el-icon><RefreshLeft /></el-icon>
              重置为原始版本
            </el-button>
          </div>
        </el-col>
      </el-row>

      <!-- 结果对比区域 -->
      <el-divider content-position="left">输出结果对比</el-divider>
      
      <el-row :gutter="20">
        <el-col :xs="24" :sm="24" :md="12" :lg="12">
          <div class="result-section">
            <div class="section-header">
              <span class="section-title">A版本输出</span>
              <el-tag v-if="resultA.status === 'loading'" type="info">
                <el-icon class="is-loading"><Loading /></el-icon>
                生成中...
              </el-tag>
              <el-tag v-else-if="resultA.status === 'success'" type="success">完成</el-tag>
              <el-tag v-else-if="resultA.status === 'error'" type="danger">失败</el-tag>
            </div>
            <div class="result-content markdown-rendered" v-html="renderMarkdown(resultA.content)"></div>
            <div v-if="resultA.tokenUsage" class="result-meta">
              <el-tag size="small">Tokens: {{ resultA.tokenUsage.totalTokens }}</el-tag>
              <el-tag size="small" type="info">耗时: {{ resultA.duration }}ms</el-tag>
            </div>
          </div>
        </el-col>

        <el-col :xs="24" :sm="24" :md="12" :lg="12">
          <div class="result-section">
            <div class="section-header">
              <span class="section-title">B版本输出</span>
              <el-tag v-if="resultB.status === 'loading'" type="info">
                <el-icon class="is-loading"><Loading /></el-icon>
                生成中...
              </el-tag>
              <el-tag v-else-if="resultB.status === 'success'" type="success">完成</el-tag>
              <el-tag v-else-if="resultB.status === 'error'" type="danger">失败</el-tag>
            </div>
            <div class="result-content markdown-rendered" v-html="renderMarkdown(resultB.content)"></div>
            <div v-if="resultB.tokenUsage" class="result-meta">
              <el-tag size="small">Tokens: {{ resultB.tokenUsage.totalTokens }}</el-tag>
              <el-tag size="small" type="info">耗时: {{ resultB.duration }}ms</el-tag>
            </div>
          </div>
        </el-col>
      </el-row>
    </el-card>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { templateAPI, modelConfigAPI, promptTestAPI } from '@/api'
import { useResponsive } from '@/composables/useResponsive'
import { useMarkdown } from '@/composables/useMarkdown'
import { useSSEStream } from '@/composables/useSSEStream'

const { isMobile } = useResponsive()
const { renderMarkdown } = useMarkdown()
const { fetchSSE } = useSSEStream()

const config = ref({
  templateName: '',
  model: '',
  stream: false,  // 对比测试默认使用非流式
  variables: ''
})

const templates = ref([])
const availableModels = ref([])
const promptA = ref('')
const promptB = ref('')
const comparing = ref(false)

const resultA = ref({
  status: '',  // loading, success, error
  content: '',
  tokenUsage: null,
  duration: 0
})

const resultB = ref({
  status: '',
  content: '',
  tokenUsage: null,
  duration: 0
})

const canCompare = computed(() => {
  return config.value.templateName && 
         config.value.model && 
         promptA.value && 
         promptB.value && 
         config.value.variables
})

onMounted(async () => {
  await Promise.all([
    loadTemplates(),
    loadModels()
  ])
})

// 加载模板列表
const loadTemplates = async () => {
  try {
    templates.value = await templateAPI.getAll()
  } catch (error) {
    ElMessage.error('加载模板列表失败')
    console.error(error)
  }
}

// 加载模型列表
const loadModels = async () => {
  try {
    const models = await modelConfigAPI.getAll()
    availableModels.value = models.map(m => ({
      code: m.modelCode,
      name: m.modelName,
      provider: m.provider
    }))
    
    if (availableModels.value.length > 0 && !config.value.model) {
      config.value.model = availableModels.value[0].code
    }
  } catch (error) {
    ElMessage.error('加载模型列表失败')
    console.error(error)
  }
}

// 模板变更
const handleTemplateChange = async () => {
  try {
    const template = await templateAPI.getByName(config.value.templateName)
    promptA.value = template.templateContent
    promptB.value = template.templateContent
    
    // 清空之前的结果
    resultA.value = { status: '', content: '', tokenUsage: null, duration: 0 }
    resultB.value = { status: '', content: '', tokenUsage: null, duration: 0 }
  } catch (error) {
    ElMessage.error('加载模板失败')
    console.error(error)
  }
}

// 加载模板变量示例
const loadTemplateVariables = async () => {
  if (!config.value.templateName) {
    ElMessage.warning('请先选择模板')
    return
  }
  
  try {
    const variables = await promptTestAPI.getTemplateVariables(config.value.templateName)
    config.value.variables = JSON.stringify(variables, null, 2)
    ElMessage.success('已加载模板示例变量')
  } catch (error) {
    ElMessage.error('加载变量示例失败')
    console.error(error)
  }
}

// 重置 B 版本
const resetPromptB = () => {
  promptB.value = promptA.value
  ElMessage.success('已重置为原始版本')
}

// 开始对比
const handleCompare = async () => {
  // 验证变量 JSON
  let variables
  try {
    variables = JSON.parse(config.value.variables)
  } catch (error) {
    ElMessage.error('变量 JSON 格式错误')
    return
  }

  comparing.value = true
  
  // 重置结果
  resultA.value = { status: 'loading', content: '', tokenUsage: null, duration: 0 }
  resultB.value = { status: 'loading', content: '', tokenUsage: null, duration: 0 }

  // 并行执行两个测试
  await Promise.all([
    executePrompt('A', promptA.value, variables),
    executePrompt('B', promptB.value, variables)
  ])

  comparing.value = false
}

// 执行 Prompt 测试
const executePrompt = async (version, promptContent, variables) => {
  const result = version === 'A' ? resultA : resultB
  const startTime = Date.now()

  try {
    let renderedPrompt = promptContent
    for (const [key, value] of Object.entries(variables)) {
      renderedPrompt = renderedPrompt.replaceAll(`{${key}}`, value)
    }

    const url = config.value.stream ? '/chat/stream' : '/chat'

    await fetchSSE(url, {
      conversationId: `comparison-${version}-${Date.now()}`,
      message: renderedPrompt,
      model: config.value.model
    }, {
      onContent: (content) => {
        result.value.content += content
      },
      onTokenUsage: (tokenUsage) => {
        result.value.tokenUsage = tokenUsage
      }
    })

    result.value.status = 'success'
    result.value.duration = Date.now() - startTime
  } catch (error) {
    console.error(`版本${version}执行失败:`, error)
    result.value.status = 'error'
    result.value.content = `执行失败: ${error.message}`
  }
}
</script>

<style scoped>
.prompt-comparison {
  max-width: 1800px;
  margin: 0 auto;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.prompt-section,
.result-section {
  border: 1px solid var(--app-border-base);
  border-radius: var(--app-radius-sm);
  padding: 16px;
  background: var(--app-bg-light);
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.section-title {
  font-weight: 600;
  font-size: 14px;
  color: var(--app-text-primary);
}

.result-content {
  min-height: 200px;
  max-height: 600px;
  overflow-y: auto;
  padding: 16px;
  background: var(--app-bg-card);
  border-radius: var(--app-radius-sm);
  line-height: 1.6;
}

.empty-result {
  color: var(--app-text-secondary);
  text-align: center;
  padding: 60px 0;
}

.result-meta {
  margin-top: 12px;
  display: flex;
  gap: 8px;
}

/* 移动端适配 */
@media (max-width: 768px) {
  .prompt-section,
  .result-section {
    margin-bottom: 20px;
  }

  :deep(.el-form-item__label) {
    width: 100% !important;
    text-align: left;
    margin-bottom: 8px;
  }

  :deep(.el-form-item__content) {
    margin-left: 0 !important;
  }

  .result-content {
    max-height: 400px;
  }
}
</style>
