// llm-frontend/src/views/TemplateManagement.vue
<template>
  <div class="template-management">
    <el-row :gutter="20">
      <!-- 左侧：模板列表 -->
      <el-col :xs="24" :sm="24" :md="10" :lg="10">
        <el-card>
          <template #header>
            <div class="card-header">
              <span>模板列表</span>
              <el-button type="primary" size="small" @click="handleCreate">
                <el-icon><Plus /></el-icon>
                <span class="btn-text">新建模板</span>
              </el-button>
            </div>
          </template>

          <el-input
            v-model="searchText"
            placeholder="搜索模板名称"
            prefix-icon="Search"
            style="margin-bottom: 16px"
          />

          <el-table
            :data="filteredTemplates"
            highlight-current-row
            @current-change="handleSelectTemplate"
            style="width: 100%"
            max-height="600"
          >
            <el-table-column prop="templateName" label="模板名称" min-width="180" />
            <el-table-column prop="category" label="分类" width="100" class-name="hidden-xs-only">
              <template #default="{ row }">
                <el-tag size="small">{{ row.category }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column label="操作" width="100">
              <template #default="{ row }">
                <el-button
                  type="danger"
                  size="small"
                  link
                  @click="handleDelete(row)"
                >
                  删除
                </el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-card>
      </el-col>

      <!-- 右侧：模板详情/编辑 -->
      <el-col :xs="24" :sm="24" :md="14" :lg="14">
        <el-card class="detail-card">
          <template #header>
            <div class="card-header">
              <span>{{ isEditing ? '编辑模板' : '模板详情' }}</span>
              <div class="action-buttons">
                <el-button
                  v-if="!isEditing && selectedTemplate"
                  type="primary"
                  size="small"
                  @click="handleEdit"
                >
                  <el-icon><Edit /></el-icon>
                  <span class="btn-text">编辑</span>
                </el-button>
                <el-button
                  v-if="isEditing"
                  type="success"
                  size="small"
                  @click="handleSave"
                  :loading="saving"
                >
                  <el-icon><Check /></el-icon>
                  <span class="btn-text">保存</span>
                </el-button>
                <el-button
                  v-if="isEditing"
                  size="small"
                  @click="handleCancel"
                >
                  <el-icon><Close /></el-icon>
                  <span class="btn-text">取消</span>
                </el-button>
              </div>
            </div>
          </template>

          <div v-if="!selectedTemplate && !isCreating" class="empty-state">
            <el-empty description="请选择或创建一个模板" />
          </div>

          <el-form
            v-else
            :model="editForm"
            :label-width="isMobile ? '100%' : '120px'"
            :label-position="isMobile ? 'top' : 'right'"
            :disabled="!isEditing"
          >
            <el-form-item label="模板名称">
              <el-input
                v-model="editForm.templateName"
                placeholder="例如：content-optimization"
                :disabled="!isCreating"
              />
            </el-form-item>

            <el-form-item label="分类">
              <el-select v-model="editForm.category" placeholder="请选择分类" style="width: 100%">
                <el-option label="content - 内容创作" value="content" />
                <el-option label="chat - 对话交互" value="chat" />
                <el-option label="development - 开发辅助" value="development" />
                <el-option label="analysis - 数据分析" value="analysis" />
                <el-option label="translation - 翻译转换" value="translation" />
              </el-select>
            </el-form-item>

            <el-form-item label="描述">
              <el-input
                v-model="editForm.description"
                type="textarea"
                :rows="2"
                placeholder="模板的简要描述"
              />
            </el-form-item>

            <el-form-item label="模板内容">
              <el-input
                v-model="editForm.templateContent"
                type="textarea"
                :rows="12"
                placeholder="使用 {variableName} 作为变量占位符"
                class="template-content"
              />
              <div class="help-text">
                <el-icon><InfoFilled /></el-icon>
                提示：使用 {variableName} 格式定义变量，例如 {userQuestion}、{platformCharacteristics}
              </div>
            </el-form-item>

            <el-form-item label="变量示例">
              <el-input
                v-model="editForm.variableExamples"
                type="textarea"
                :rows="8"
                placeholder='JSON 格式的变量示例，例如：{"name": "张三", "age": "25"}'
                class="template-content"
              />
              <div class="help-text">
                <el-icon><InfoFilled /></el-icon>
                提示：用于 Prompt 测试时的默认变量值，必须是有效的 JSON 格式
              </div>
              <el-button
                v-if="isEditing"
                size="small"
                type="primary"
                link
                @click="formatJSON"
                style="margin-top: 8px"
              >
                <el-icon><MagicStick /></el-icon>
                格式化 JSON
              </el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { templateAPI } from '@/api'
import { useResponsive } from '@/composables/useResponsive'

const { isMobile } = useResponsive()

const templates = ref([])
const selectedTemplate = ref(null)
const searchText = ref('')
const isEditing = ref(false)
const isCreating = ref(false)
const saving = ref(false)

const editForm = ref({
  templateName: '',
  category: '',
  description: '',
  templateContent: '',
  variableExamples: ''
})

// 过滤后的模板列表
const filteredTemplates = computed(() => {
  if (!searchText.value) return templates.value
  return templates.value.filter(t =>
    t.templateName.toLowerCase().includes(searchText.value.toLowerCase())
  )
})

onMounted(async () => {
  await loadTemplates()
})

// 加载模板列表
const loadTemplates = async () => {
  try {
    templates.value = await templateAPI.getAll()
  } catch (error) {
    console.error('加载模板失败:', error)
  }
}

// 选择模板
const handleSelectTemplate = (row) => {
  if (!row) return
  selectedTemplate.value = row
  isEditing.value = false
  isCreating.value = false
  editForm.value = { ...row }
}

// 创建模板
const handleCreate = () => {
  selectedTemplate.value = null
  isEditing.value = true
  isCreating.value = true
  editForm.value = {
    templateName: '',
    category: 'content',
    description: '',
    templateContent: '',
    variableExamples: ''
  }
}

// 编辑模板
const handleEdit = () => {
  isEditing.value = true
}

// 保存模板
const handleSave = async () => {
  if (!editForm.value.templateName) {
    ElMessage.warning('请输入模板名称')
    return
  }
  if (!editForm.value.templateContent) {
    ElMessage.warning('请输入模板内容')
    return
  }

  // 验证变量示例是否为有效 JSON
  if (editForm.value.variableExamples) {
    try {
      JSON.parse(editForm.value.variableExamples)
    } catch (error) {
      ElMessage.warning('变量示例必须是有效的 JSON 格式')
      return
    }
  }

  saving.value = true
  try {
    await templateAPI.save(editForm.value)
    ElMessage.success('保存成功')
    await loadTemplates()
    isEditing.value = false
    isCreating.value = false
    
    // 重新选中当前模板
    const saved = templates.value.find(t => t.templateName === editForm.value.templateName)
    if (saved) {
      selectedTemplate.value = saved
    }
  } catch (error) {
    ElMessage.error('保存失败')
    console.error('保存失败:', error)
  } finally {
    saving.value = false
  }
}

// 格式化 JSON
const formatJSON = () => {
  if (!editForm.value.variableExamples) {
    ElMessage.warning('请先输入 JSON 内容')
    return
  }
  
  try {
    const parsed = JSON.parse(editForm.value.variableExamples)
    editForm.value.variableExamples = JSON.stringify(parsed, null, 2)
    ElMessage.success('格式化成功')
  } catch (error) {
    ElMessage.error('JSON 格式错误，无法格式化')
  }
}

// 取消编辑
const handleCancel = () => {
  if (isCreating.value) {
    selectedTemplate.value = null
    isCreating.value = false
  } else if (selectedTemplate.value) {
    editForm.value = { ...selectedTemplate.value }
  }
  isEditing.value = false
}

// 删除模板
const handleDelete = async (row) => {
  try {
    await ElMessageBox.confirm(
      `确定要删除模板 "${row.templateName}" 吗？`,
      '确认删除',
      {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }
    )

    await templateAPI.delete(row.templateName)
    ElMessage.success('删除成功')
    await loadTemplates()
    
    if (selectedTemplate.value?.templateName === row.templateName) {
      selectedTemplate.value = null
    }
  } catch (error) {
    if (error !== 'cancel') {
      console.error('删除失败:', error)
    }
  }
}
</script>

<style scoped>
.template-management {
  max-width: 1600px;
  margin: 0 auto;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.empty-state {
  padding: 60px 0;
}

.template-content {
  font-family: 'Courier New', monospace;
  font-size: 14px;
}

.help-text {
  margin-top: 8px;
  color: var(--app-text-secondary);
  font-size: 12px;
  display: flex;
  align-items: center;
  gap: 4px;
}

/* 移动端适配 */
@media (max-width: 768px) {
  .detail-card {
    margin-top: 20px;
  }

  .card-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
  }

  .action-buttons {
    display: flex;
    gap: 8px;
    width: 100%;
  }

  .action-buttons .el-button {
    flex: 1;
  }

  .btn-text {
    display: none;
  }

  :deep(.el-form-item__label) {
    width: 100% !important;
    text-align: left;
    margin-bottom: 8px;
  }

  :deep(.el-form-item__content) {
    margin-left: 0 !important;
  }

  :deep(.hidden-xs-only) {
    display: none;
  }
}
</style>

// llm-frontend/src/views/TemplateManagement.tsx
import React, { useState, useEffect, useMemo, useCallback } from 'react'
import { 
  Plus, Search, Edit, Check, X, 
  Trash2, BoxSelect, Info, Wand2, Tag 
} from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { templateAPI } from '@/api'
import { useResponsive } from '@/hooks/useResponsive'

const TemplateManagement: React.FC = () => {
  const { isMobile } = useResponsive()

  const [templates, setTemplates] = useState<any[]>([])
  const [selectedTemplate, setSelectedTemplate] = useState<any>(null)
  const [searchText, setSearchText] = useState('')
  const [isEditing, setIsEditing] = useState(false)
  const [isCreating, setIsCreating] = useState(false)
  const [saving, setSaving] = useState(false)

  const [editForm, setEditForm] = useState({
    templateName: '',
    category: '',
    description: '',
    templateContent: '',
    variableExamples: ''
  })

  const loadTemplates = useCallback(async () => {
    try {
      const res: any = await templateAPI.getAll()
      setTemplates(res || [])
    } catch (error) {
      console.error('Failed to load templates:', error)
    }
  }, [])

  useEffect(() => {
    loadTemplates()
  }, [loadTemplates])

  const filteredTemplates = useMemo(() => {
    if (!searchText) return templates
    return templates.filter(t =>
      t.templateName.toLowerCase().includes(searchText.toLowerCase())
    )
  }, [templates, searchText])

  const handleSelectTemplate = (t: any) => {
    setSelectedTemplate(t)
    setIsEditing(false)
    setIsCreating(false)
    setEditForm({ ...t })
  }

  const handleCreate = () => {
    setSelectedTemplate(null)
    setIsEditing(true)
    setIsCreating(true)
    setEditForm({
      templateName: '',
      category: 'content',
      description: '',
      templateContent: '',
      variableExamples: ''
    })
  }

  const handleSave = async () => {
    if (!editForm.templateName || !editForm.templateContent) return

    if (editForm.variableExamples) {
      try {
        JSON.parse(editForm.variableExamples)
      } catch {
        // TODO: Toast error
        return
      }
    }

    setSaving(true)
    try {
      await templateAPI.save(editForm)
      await loadTemplates()
      setIsEditing(false)
      setIsCreating(false)
      // Update selected
      const saved = templates.find(t => t.templateName === editForm.templateName)
      if (saved) setSelectedTemplate(saved)
    } catch (error) {
      console.error('Save failed', error)
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async (t: any) => {
    if (window.confirm(`确定要删除模板 "${t.templateName}" 吗？`)) {
      try {
        await templateAPI.delete(t.templateName)
        await loadTemplates()
        if (selectedTemplate?.templateName === t.templateName) {
          setSelectedTemplate(null)
        }
      } catch (error) {
        console.error('Delete failed', error)
      }
    }
  }

  const formatJSON = () => {
    try {
      const parsed = JSON.parse(editForm.variableExamples)
      setEditForm({ ...editForm, variableExamples: JSON.stringify(parsed, null, 2) })
    } catch {
      // TODO: Toast error
    }
  }

  return (
    <div className="max-w-7xl mx-auto flex flex-col lg:flex-row gap-8 h-full overflow-hidden">
      
      {/* 左侧：模板列表轨道 */}
      <aside className={`w-full lg:w-96 flex flex-col shrink-0 transition-all ${isMobile && (selectedTemplate || isCreating) ? 'hidden' : 'flex'}`}>
        <div className="flex items-center justify-between px-4 mb-6">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 app-surface rounded-xl flex items-center justify-center text-primary">
              <Tag size={20} />
            </div>
            <h2 className="font-black tracking-tight text-lg">模板库</h2>
          </div>
          <button 
            onClick={handleCreate}
            className="w-10 h-10 app-surface rounded-xl flex items-center justify-center text-primary active:scale-90 transition-all"
          >
            <Plus size={20} />
          </button>
        </div>

        <div className="px-4 mb-6">
          <div className="app-recess rounded-2xl flex items-center gap-3 px-4 py-3 group focus-within:ring-2 ring-primary/20 transition-all">
            <Search size={16} className="text-foreground/20" />
            <input 
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
              placeholder="搜索模板..."
              className="bg-transparent border-none focus:outline-none text-sm w-full font-bold placeholder:text-foreground/10"
            />
          </div>
        </div>

        <div className="flex-1 app-recess rounded-[3rem] p-4 overflow-y-auto no-scrollbar space-y-3">
          {filteredTemplates.map((t) => (
            <div 
              key={t.templateName}
              onClick={() => handleSelectTemplate(t)}
              className={`p-5 rounded-[2rem] cursor-pointer transition-all flex items-center justify-between group ${
                selectedTemplate?.templateName === t.templateName ? 'app-surface text-primary z-10' : 'hover:bg-foreground/5 text-foreground/60'
              }`}
            >
              <div className="flex-1 min-w-0 pr-4">
                <p className="text-sm font-black truncate">{t.templateName}</p>
                <div className="flex items-center gap-2 mt-1">
                  <span className="text-[9px] font-bold uppercase tracking-widest opacity-40">{t.category}</span>
                </div>
              </div>
              <button 
                onClick={(e) => { e.stopPropagation(); handleDelete(t); }}
                className="p-2 rounded-xl app-surface text-red-500/20 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-all"
              >
                <Trash2 size={14} />
              </button>
            </div>
          ))}
          {filteredTemplates.length === 0 && (
            <div className="py-20 text-center opacity-20">
              <BoxSelect size={48} className="mx-auto mb-4" />
              <p className="text-xs font-black tracking-widest uppercase">No Templates</p>
            </div>
          )}
        </div>
      </aside>

      {/* 右侧：编辑/详情面板 */}
      <main className={`flex-1 flex flex-col min-w-0 ${isMobile && !selectedTemplate && !isCreating ? 'hidden' : 'flex'}`}>
        <AnimatePresence mode="wait">
          {!selectedTemplate && !isCreating ? (
            <motion.div 
              key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="flex-1 flex items-center justify-center"
            >
              <div className="app-surface p-16 rounded-[4rem] text-center space-y-6">
                <div className="w-20 h-20 app-recess rounded-[2rem] mx-auto flex items-center justify-center text-foreground/10">
                  <Edit size={32} />
                </div>
                <p className="text-sm font-bold text-foreground/30 uppercase tracking-[0.3em]">SELECT A TEMPLATE</p>
              </div>
            </motion.div>
          ) : (
            <motion.div 
              key="editor" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}
              className="flex-1 flex flex-col app-surface rounded-[4rem] overflow-hidden border border-white/40"
            >
              <header className="h-20 flex items-center px-10 border-b border-foreground/5 bg-white/5 backdrop-blur-xl">
                {isMobile && (
                  <button onClick={() => setSelectedTemplate(null)} className="mr-4 w-8 h-8 app-surface rounded-full flex items-center justify-center text-foreground/40 active:scale-90">
                    <X size={16} />
                  </button>
                )}
                <h3 className="text-lg font-black tracking-tight flex-1 truncate">
                  {isCreating ? 'NEW TEMPLATE' : (isEditing ? 'EDITING...' : 'TEMPLATE VIEW')}
                </h3>
                <div className="flex items-center gap-3">
                  {!isEditing ? (
                    <button onClick={() => setIsEditing(true)} className="px-6 py-2.5 app-surface rounded-2xl text-primary text-[11px] font-black tracking-widest active:scale-95 transition-all">EDIT</button>
                  ) : (
                    <>
                      <button onClick={() => { setIsEditing(false); if (isCreating) setSelectedTemplate(null); }} className="px-6 py-2.5 app-surface rounded-2xl text-foreground/40 text-[11px] font-black tracking-widest active:scale-95 transition-all">CANCEL</button>
                      <button onClick={handleSave} disabled={saving} className="px-6 py-2.5 app-surface rounded-2xl text-primary text-[11px] font-black tracking-widest active:scale-95 transition-all shadow-lg disabled:opacity-50">
                        {saving ? 'SAVING...' : 'SAVE'}
                      </button>
                    </>
                  )}
                </div>
              </header>

              <div className="flex-1 overflow-y-auto p-10 space-y-8 no-scrollbar">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black tracking-widest text-foreground/30 uppercase px-4">Identifier</label>
                    <div className="app-recess rounded-[1.5rem] p-1">
                      <input 
                        value={editForm.templateName}
                        onChange={(e) => setEditForm({...editForm, templateName: e.target.value})}
                        disabled={!isCreating}
                        placeholder="e.g. content-optimization"
                        className="w-full bg-transparent border-none focus:outline-none px-5 py-4 text-sm font-bold disabled:opacity-50"
                      />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black tracking-widest text-foreground/30 uppercase px-4">Category</label>
                    <div className="app-recess rounded-[1.5rem] p-1">
                      <select 
                        value={editForm.category}
                        onChange={(e) => setEditForm({...editForm, category: e.target.value})}
                        disabled={!isEditing}
                        className="w-full bg-transparent border-none focus:outline-none px-5 py-4 text-sm font-bold appearance-none cursor-pointer disabled:opacity-50"
                      >
                        <option value="content">Content Creation</option>
                        <option value="chat">Interactive Chat</option>
                        <option value="development">Dev Assistance</option>
                        <option value="analysis">Data Analysis</option>
                        <option value="translation">Translation</option>
                      </select>
                    </div>
                  </div>
                </div>

                <div className="space-y-2">
                  <label className="text-[10px] font-black tracking-widest text-foreground/30 uppercase px-4">Description</label>
                  <div className="app-recess rounded-[1.5rem] p-1">
                    <textarea 
                      value={editForm.description}
                      onChange={(e) => setEditForm({...editForm, description: e.target.value})}
                      disabled={!isEditing}
                      rows={2}
                      placeholder="Brief overview of this template's purpose..."
                      className="w-full bg-transparent border-none focus:outline-none px-5 py-4 text-sm resize-none disabled:opacity-50"
                    />
                  </div>
                </div>

                <div className="space-y-4">
                  <div className="flex items-center justify-between px-4">
                    <label className="text-[10px] font-black tracking-widest text-foreground/30 uppercase">Template Payload</label>
                    <div className="flex items-center gap-2 text-[9px] font-bold text-primary/40 uppercase tracking-widest">
                      <Info size={10} />
                      Use {'{variable}'} as placeholders
                    </div>
                  </div>
                  <div className="app-recess rounded-[2.5rem] p-1">
                    <textarea 
                      value={editForm.templateContent}
                      onChange={(e) => setEditForm({...editForm, templateContent: e.target.value})}
                      disabled={!isEditing}
                      rows={12}
                      className="w-full bg-transparent border-none focus:outline-none px-6 py-6 text-sm font-mono leading-relaxed resize-none disabled:opacity-50"
                    />
                  </div>
                </div>

                <div className="space-y-4">
                  <div className="flex items-center justify-between px-4">
                    <label className="text-[10px] font-black tracking-widest text-foreground/30 uppercase">Variable Examples (JSON)</label>
                    {isEditing && (
                      <button onClick={formatJSON} className="flex items-center gap-2 text-[9px] font-black text-primary hover:opacity-80 transition-all uppercase tracking-widest">
                        <Wand2 size={12} />
                        Format JSON
                      </button>
                    )}
                  </div>
                  <div className="app-recess rounded-[2rem] p-1">
                    <textarea 
                      value={editForm.variableExamples}
                      onChange={(e) => setEditForm({...editForm, variableExamples: e.target.value})}
                      disabled={!isEditing}
                      rows={8}
                      placeholder='{"name": "John Doe", "role": "Expert"}'
                      className="w-full bg-transparent border-none focus:outline-none px-6 py-6 text-sm font-mono leading-relaxed resize-none disabled:opacity-50"
                    />
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

    </div>
  )
}

export default TemplateManagement
